#!/bin/bash

CSV_FILE=~/cloud/lch-tools/'LXC SaaS Customer Environments - Clusters.csv'

# 1. Ask for Support Account Code (col e)
read -p "Enter Support Account Code: " ACCOUNT
 # convert to uppercase for case-insensitive match
ACCOUNT_UPPER=$(echo "$ACCOUNT" | tr '[:lower:]' '[:upper:]')

# 2. Find matching rows in CSV (col c)
# $5 = Support Account Code. $3 = Env
MATCHES=($(awk -F',' -v acc="$ACCOUNT_UPPER" 'toupper ($5) == acc {print $3}' "$CSV_FILE"))

# 3. List environments and ask user to choose
if [ ${#MATCHES[@]} -eq 0 ]; then
    echo "Support Account Code '$ACCOUNT' not found."
    exit 1
fi

#matches
echo "Found the following environments for $ACCOUNT_UPPER:"

#returns array
for i in "${!MATCHES[@]}"; do
    echo "$((i+1))) ${MATCHES[$i]}"
done

#select one
read -p "Choose Environment [1-${#MATCHES[@]}]: " ENV_IDX

#validate
if [[ "$ENV_IDX" -lt 1 || "$ENV_IDX" -gt ${#MATCHES[@]} ]]; then
    echo "Invalid selection. Exiting."
    exit 1
fi

#setting the env
SELECTED_ENV=${MATCHES[$((ENV_IDX-1))]}

echo "You selected: $SELECTED_ENV"

# find the line in the csv based on the user imput
LINE_NUM=$(awk -F',' -v env="$SELECTED_ENV" '$3 == env {print NR}' "$CSV_FILE")

# extract the fields based on the env string
DXPC_PROJECT=$(awk -F',' "NR==$LINE_NUM {print \$3}" "$CSV_FILE")
MW_DAY=$(awk -F',' "NR==$LINE_NUM {print \$6}" "$CSV_FILE")
MW_TIME=$(awk -F',' "NR==$LINE_NUM {print \$7}" "$CSV_FILE")

# 4. Build the LCH template
# title input


# ticket context

# numbered requests (optional) already pulled

# maintenace window (optional) already pulled


# 6. Print to terminal 
